branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  pizza-dev:
    branch: master
    repository: pizza-dev
global:
  application_name: pizza
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: pizza
  sc: git
  workspace_type: Application
